# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.2.4'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'TestConnection'
    backendAzureRmResourceGroupName: 'terraform-rg-ik'
    backendAzureRmStorageAccountName: 'storagetfaccount'
    backendAzureRmContainerName: 'storagetfcontainer'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'TestConnection'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
