
steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'TestConnection'
    backendAzureRmResourceGroupName: 'terraform-rg-ik'
    backendAzureRmStorageAccountName: 'storagetfaccount'
    backendAzureRmContainerName: 'storagetfcontainer'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'TestConnection'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
